
name: "PR Analyzer"
description: "Analyzes a pull request and comments a summary."
inputs:
  github_token:
    description: "Token for API access"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"

  #test


